from typing import Optional, Union, Type, Dict
from gameboy_worlds.emulation.parser import StateParser
from gameboy_worlds.emulation.tracker import StateTracker
from gameboy_worlds.emulation.emulator import Emulator

from gameboy_worlds.emulation.pokemon.parsers import (
    MemoryBasedPokemonCrystalStateParser,
    MemoryBasedPokemonRedStateParser,
    PokemonBrownStateParser,
    PokemonStarBeastsStateParser,
    PokemonStarBeastsCometStateParser,
    PokemonCrystalStateParser,
    PokemonPrismStateParser,
    PokemonFoolsGoldStateParser,
)
from gameboy_worlds.emulation.pokemon.trackers import (
    PokemonOCRTracker,
    PokemonRedStarterTracker,
    PokemonRedCenterTestTracker,
    PokemonRedMtMoonTestTracker,
    PokemonRedSpeakToBillTestTracker,
    PokemonRedPickupPokeballTestTracker,
    PokemonRedSpeakToBillTestTracker,
    PokemonRedPickupPokeballTestTracker,
    PokemonRedReadTrainersTipsSignTestTracker,
    PokemonRedSpeakToCinnabarGymAideCompleteTestTracker,
    PokemonRedSpeakToCinnabarMonkTestTracker,
    PokemonRedDefeatedBrockTestTracker,
    PokemonRedDefeatedLassTestTracker,
    PokemonRedCaughtPidgeyTestTracker,
    PokemonRedCaughtPikachuTestTracker,
    PokemonRedBoughtPotionAtPewterPokemartTestTracker,
    PokemonRedUsedPotionOnCharmanderTestTracker,
    PokemonRedOpenMapTestTracker,
    PokemonRedUsedNotVeryEffectiveAttackOnSeakingTestTracker,
    PokemonRedChampionshipTestTracker,
    PokemonBrownChampionshipTestTracker,
    PokemonCrystalChampionshipTestTracker,
    PokemonPrismChampionshipTestTracker,
    PokemonRedTriedBuyBikeTestTracker,
    PokemonRedClickVolcanobadgeTestTracker,
    PokemonRedOpenedCeruleanHouseMapTestTracker,
    PokemonRedSquirtleFaintedTestTracker,
    PokemonRedClickedSwitchTestTracker,
    PokemonRedUsedSurfAshTestTracker,
    PokemonRedSold1PsychicTestTracker,
    PokemonRedEncounteredGhostTestTracker,
    PokemonRedRateMewNameTestTracker,
    PokemonRedReadLetterTestTracker,
    PokemonRedSpokeToEliteFourTestTracker,
    PokemonRedUsedSuperRodTestTracker,
    PokemonRedLookedIntoBinocularsTestTracker,
    PokemonRedSpokeToPikachuTestTracker,
    PokemonRedOutsideSilfCoTestTracker,
    PokemonRedOutsideRobbedHouseBackTestTracker,
    PokemonRedGaveMewtwoToDaycareTestTracker,
    PokemonRedReadSaffronSignTestTracker,
    PokemonRedMarioGamePlayedTestTracker,
    PokemonRedTossedUltraballTestTracker,
    PokemonRedOutsideSeafoamIslandsTestTracker,
    PokemonRedFlyToPalletTownFromCinnabarTestTracker,
    PokemonRedWithdrewStaryuTestTracker,
    PokemonRedUsedToxicOnPidgeottoTestTracker,
    PokemonRedSwitchedToStaryuTestTracker,
    PokemonRedCaughtGoldeenTestTracker,
    PokemonRedTriedToTeachStaryuToxicTestTracker,
    PokemonRedPlayFluteTestTracker,
    PokemonRedOpenedSquirtlePokedexTestTracker,
    PokemonRedOpenedBlastoiseStatusTestTracker,
    PokemonRedCharizardMovesTestTracker,
    PokemonRedSpokeToLeaderTestTracker,
    PokemonRedReachGiovanniAreaTestTracker,
    PokemonCrystalEnteredCherrygroveCentreTestTracker,
    PokemonCrystalWatchedTvTestTracker,
    PokemonCrystalSawMirrorTestTracker,
    PokemonCrystalSpokeToChildTestTracker,
    PokemonCrystalGotBerryTestTracker,
    PokemonCrystalTookDragonairItemTestTracker,
    PokemonCrystalGavePidgeotCleanseTagTestTracker,
    PokemonCrystalOpenedTyphlosionEntryTestTracker,
    PokemonCrystalExitedMtMortarTestTracker,
    PokemonCrystalGotBiteTestTracker,
    PokemonCrystalReadElmComputerTestTracker,
    PokemonCrystalSpokeToAideTestTracker,
    PokemonCrystalUsedEscapeRopeTestTracker,
    PokemonCrystalSpokeToVioletGymLeaderTestTracker,
    PokemonCrystalBoughtAntidoteTestTracker,
    PokemonCrystalSoldReviveTestTracker,
    PokemonCrystalPidgeotLearnedToxicTestTracker,
    PokemonCrystalGotAlanNumberTestTracker,
    PokemonCrystalInteractedCutTreeTestTracker,
    PokemonCrystalPickedUpParlzHealTestTracker,
    PokemonCrystalReadBookTestTracker,
    PokemonCrystalSpokeToMortyTestTracker,
    PokemonCrystalEnteredBurnedTowerTestTracker,
    PokemonCrystalMiltankSadTestTracker,
    PokemonCrystalGotGoodRodTestTracker,
    PokemonCrystalEnteredLighthouseTestTracker,
    PokemonCrystalSpokeToRedHairGirlTestTracker,
    PokemonCrystalForgotGustTestTracker,
    PokemonCrystalLeftIcePathTestTracker,
    PokemonCrystalIceMazeOtherSideTestTracker,
    PokemonCrystalUsedSuperEffectiveAttackTestTracker,
    PokemonCrystalCaughtDelibirdTestTracker,
    PokemonCrystalEncounteredTangelaTestTracker,
    PokemonCrystalSpokeToSlowpokeTestTracker,
    PokemonCrystalGotCharcoalTestTracker,
    PokemonCrystalSpokeToAzaleaGymTestTracker,
    PokemonCrystalGotFastballTestTracker,
    PokemonCrystalGaveKurtApricotTestTracker,
    PokemonCrystalCantDoThatTestTracker,
    PokemonCrystalUsedHeadbuttTestTracker,
    PokemonCrystalTookSuicunePicTestTracker,
    PokemonCrystalUsedSurfTestTracker,
    PokemonCrystalSeerSawAlakazamTestTracker,
    PokemonCrystalOpenedMailboxTestTracker,
    PokemonCrystalCalledMomTestTracker,
    PokemonCrystalCaughtPonytaTestTracker,
    PokemonCrystalUsedFlashTestTracker,
    PokemonCrystalBattleTowerExplanationTestTracker,
    PokemonCrystalDefeatedWillTestTracker,
    PokemonCrystalDefeatedKogaTestTracker,
)
from gameboy_worlds.emulation.pokemon.emulators import PokemonEmulator


GAME_TO_GB_NAME = {
    "pokemon_red": "PokemonRed.gb",
    "pokemon_brown": "PokemonBrown.gb",
    "pokemon_starbeasts": "PokemonStarBeasts.gb",
    "pokemon_starbeasts_comet": "PokemonStarBeastsComet.gb",
    "pokemon_crystal": "PokemonCrystal.gbc",
    "pokemon_fools_gold": "PokemonFoolsGold.gbc",
    "pokemon_prism": "PokemonPrism.gbc",
}
""" Expected save name for each game. Save the file to <storage_dir_from_config_file>/<game_name>_rom_data/<gb_name>"""

STRONGEST_PARSERS: Dict[str, Type[StateParser]] = {
    "pokemon_red": MemoryBasedPokemonRedStateParser,
    "pokemon_brown": PokemonBrownStateParser,
    "pokemon_crystal": MemoryBasedPokemonCrystalStateParser,
    "pokemon_starbeasts": PokemonStarBeastsStateParser,
    "pokemon_starbeasts_comet": PokemonStarBeastsCometStateParser,
    "pokemon_fools_gold": PokemonFoolsGoldStateParser,
    "pokemon_prism": PokemonPrismStateParser,
}
""" Mapping of game names to their corresponding strongest StateParser classes. 
Unless you have a very good reason, you should always use the STRONGEST possible parser for a given game. 
The parser itself does not affect performance, as for it to perform a read / screen comparison operation , it must be called upon by the state tracker.
This means there is never a reason to use a weaker parser. 
"""


AVAILABLE_STATE_TRACKERS: Dict[str, Dict[str, Type[StateTracker]]] = {
    "pokemon_red": {
        "default": PokemonOCRTracker,
        "starter_example": PokemonRedStarterTracker,
        "viridian_center_test": PokemonRedCenterTestTracker,
        "mt_moon_test": PokemonRedMtMoonTestTracker,
        "speak_to_bill_test": PokemonRedSpeakToBillTestTracker,
        "pickup_pokeball_test": PokemonRedPickupPokeballTestTracker,
        "read_trainers_tips_sign_test": PokemonRedReadTrainersTipsSignTestTracker,
        "speak_to_cinnabar_gym_aide_complete_test": PokemonRedSpeakToCinnabarGymAideCompleteTestTracker,
        "speak_to_cinnabar_monk_test": PokemonRedSpeakToCinnabarMonkTestTracker,
        "defeated_brock_test": PokemonRedDefeatedBrockTestTracker,
        "defeated_lass_test": PokemonRedDefeatedLassTestTracker,
        "caught_pidgey_test": PokemonRedCaughtPidgeyTestTracker,
        "caught_pikachu_test": PokemonRedCaughtPikachuTestTracker,
        "bought_potion_at_pewter_pokemart_test": PokemonRedBoughtPotionAtPewterPokemartTestTracker,
        "used_potion_on_charmander_test": PokemonRedUsedPotionOnCharmanderTestTracker,
        "open_map_test": PokemonRedOpenMapTestTracker,
        "used_not_very_effective_attack": PokemonRedUsedNotVeryEffectiveAttackOnSeakingTestTracker,
        "collect_championship_test": PokemonRedChampionshipTestTracker,
        "tried_buy_bike": PokemonRedTriedBuyBikeTestTracker,
        "click_volcanobadge": PokemonRedClickVolcanobadgeTestTracker,
        "opened_cerulean_house_map": PokemonRedOpenedCeruleanHouseMapTestTracker,
        "squirtle_fainted": PokemonRedSquirtleFaintedTestTracker,
        "clicked_switch": PokemonRedClickedSwitchTestTracker,
        "used_surf_ash": PokemonRedUsedSurfAshTestTracker,
        "sold_1_psychic": PokemonRedSold1PsychicTestTracker,
        "encountered_ghost": PokemonRedEncounteredGhostTestTracker,
        "rate_mew_name": PokemonRedRateMewNameTestTracker,
        "read_letter": PokemonRedReadLetterTestTracker,
        "spoke_to_elite_four": PokemonRedSpokeToEliteFourTestTracker,
        "used_super_rod": PokemonRedUsedSuperRodTestTracker,
        "looked_into_binoculars": PokemonRedLookedIntoBinocularsTestTracker,
        "spoke_to_pikachu": PokemonRedSpokeToPikachuTestTracker,
        "outside_silf_co": PokemonRedOutsideSilfCoTestTracker,
        "outside_robbed_house_back": PokemonRedOutsideRobbedHouseBackTestTracker,
        "gave_mewtwo_to_daycare": PokemonRedGaveMewtwoToDaycareTestTracker,
        "read_saffron_sign": PokemonRedReadSaffronSignTestTracker,
        "mario_game_played": PokemonRedMarioGamePlayedTestTracker,
        "tossed_ultraball": PokemonRedTossedUltraballTestTracker,
        "outside_seafoam_islands": PokemonRedOutsideSeafoamIslandsTestTracker,
        "fly_to_pallet_town_from_cinnabar": PokemonRedFlyToPalletTownFromCinnabarTestTracker,
        "withdrew_staryu": PokemonRedWithdrewStaryuTestTracker,
        "used_toxic_on_pidgeotto": PokemonRedUsedToxicOnPidgeottoTestTracker,
        "switched_to_staryu": PokemonRedSwitchedToStaryuTestTracker,
        "caught_goldeen": PokemonRedCaughtGoldeenTestTracker,
        "tried_to_teach_staryu_toxic": PokemonRedTriedToTeachStaryuToxicTestTracker,
        "play_flute": PokemonRedPlayFluteTestTracker,
        "opened_squirtle_pokedex": PokemonRedOpenedSquirtlePokedexTestTracker,
        "opened_blastoise_status": PokemonRedOpenedBlastoiseStatusTestTracker,
        "charizard_moves": PokemonRedCharizardMovesTestTracker,
        "spoke_to_leader": PokemonRedSpokeToLeaderTestTracker,
        "reach_giovanni_area": PokemonRedReachGiovanniAreaTestTracker,
    },
    "pokemon_brown": {
        "default": PokemonOCRTracker,
        "collect_championship_test": PokemonBrownChampionshipTestTracker,
    },
    "pokemon_crystal": {
        "default": PokemonOCRTracker,
        "collect_championship_test": PokemonCrystalChampionshipTestTracker,
        "entered_cherrygrove_centre": PokemonCrystalEnteredCherrygroveCentreTestTracker,
        "watched_tv": PokemonCrystalWatchedTvTestTracker,
        "saw_mirror": PokemonCrystalSawMirrorTestTracker,
        "spoke_to_child": PokemonCrystalSpokeToChildTestTracker,
        "got_berry": PokemonCrystalGotBerryTestTracker,
        "took_dragonair_item": PokemonCrystalTookDragonairItemTestTracker,
        "gave_pidgeot_cleanse_tag": PokemonCrystalGavePidgeotCleanseTagTestTracker,
        "opened_typhlosion_entry": PokemonCrystalOpenedTyphlosionEntryTestTracker,
        "exited_mt_mortar": PokemonCrystalExitedMtMortarTestTracker,
        "got_bite": PokemonCrystalGotBiteTestTracker,
        "read_elm_computer": PokemonCrystalReadElmComputerTestTracker,
        "spoke_to_aide": PokemonCrystalSpokeToAideTestTracker,
        "used_escape_rope": PokemonCrystalUsedEscapeRopeTestTracker,
        "spoke_to_violet_gym_leader": PokemonCrystalSpokeToVioletGymLeaderTestTracker,
        "bought_antidote": PokemonCrystalBoughtAntidoteTestTracker,
        "sold_revive": PokemonCrystalSoldReviveTestTracker,
        "pidgeot_learned_toxic": PokemonCrystalPidgeotLearnedToxicTestTracker,
        "got_alan_number": PokemonCrystalGotAlanNumberTestTracker,
        "interacted_cut_tree": PokemonCrystalInteractedCutTreeTestTracker,
        "picked_up_parlz_heal": PokemonCrystalPickedUpParlzHealTestTracker,
        "read_book": PokemonCrystalReadBookTestTracker,
        "spoke_to_morty": PokemonCrystalSpokeToMortyTestTracker,
        "entered_burned_tower": PokemonCrystalEnteredBurnedTowerTestTracker,
        "miltank_sad": PokemonCrystalMiltankSadTestTracker,
        "got_good_rod": PokemonCrystalGotGoodRodTestTracker,
        "entered_lighthouse": PokemonCrystalEnteredLighthouseTestTracker,
        "spoke_to_red_hair_girl": PokemonCrystalSpokeToRedHairGirlTestTracker,
        "forgot_gust": PokemonCrystalForgotGustTestTracker,
        "left_ice_path": PokemonCrystalLeftIcePathTestTracker,
        "ice_maze_other_side": PokemonCrystalIceMazeOtherSideTestTracker,
        "used_super_effective_attack": PokemonCrystalUsedSuperEffectiveAttackTestTracker,
        "caught_delibird": PokemonCrystalCaughtDelibirdTestTracker,
        "encountered_tangela": PokemonCrystalEncounteredTangelaTestTracker,
        "spoke_to_slowpoke": PokemonCrystalSpokeToSlowpokeTestTracker,
        "got_charcoal": PokemonCrystalGotCharcoalTestTracker,
        "spoke_to_azalea_gym": PokemonCrystalSpokeToAzaleaGymTestTracker,
        "got_fastball": PokemonCrystalGotFastballTestTracker,
        "gave_kurt_apricot": PokemonCrystalGaveKurtApricotTestTracker,
        "cant_do_that": PokemonCrystalCantDoThatTestTracker,
        "used_headbutt": PokemonCrystalUsedHeadbuttTestTracker,
        "took_suicune_pic": PokemonCrystalTookSuicunePicTestTracker,
        "used_surf": PokemonCrystalUsedSurfTestTracker,
        "seer_saw_alakazam": PokemonCrystalSeerSawAlakazamTestTracker,
        "opened_mailbox": PokemonCrystalOpenedMailboxTestTracker,
        "called_mom": PokemonCrystalCalledMomTestTracker,
        "caught_ponyta": PokemonCrystalCaughtPonytaTestTracker,
        "used_flash": PokemonCrystalUsedFlashTestTracker,
        "battle_tower_explanation": PokemonCrystalBattleTowerExplanationTestTracker,
        "defeated_will": PokemonCrystalDefeatedWillTestTracker,
        "defeated_koga": PokemonCrystalDefeatedKogaTestTracker,
    },
    "pokemon_starbeasts": {
        "default": PokemonOCRTracker,
    },
    "pokemon_starbeasts_comet": {
        "default": PokemonOCRTracker,
    },
    "pokemon_fools_gold": {
        "default": PokemonOCRTracker,
    },
    "pokemon_prism": {
        "default": PokemonOCRTracker,
        "collect_championship_test": PokemonPrismChampionshipTestTracker,
    },
}
""" Mapping of game names to their available StateTracker classes with string identifiers. """


AVAILABLE_EMULATORS: Dict[str, Dict[str, Type[Emulator]]] = {
    "pokemon_red": {
        "default": PokemonEmulator,
    },
    "pokemon_brown": {
        "default": PokemonEmulator,
    },
    "pokemon_crystal": {
        "default": PokemonEmulator,
    },
    "pokemon_starbeasts": {
        "default": PokemonEmulator,
    },
    "pokemon_starbeasts_comet": {
        "default": PokemonEmulator,
    },
    "pokemon_fools_gold": {
        "default": PokemonEmulator,
    },
    "pokemon_prism": {
        "default": PokemonEmulator,
    },
}
""" Mapping of game names to their available Emulator classes with string identifiers. """
